### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by Mehdi-Rh**
# Description

This is the first PR of the Math Magicians application. I set up the environment and tools needed to develop a React application. In the following PRs, I will develop the actual application.

## Type of change

* Set Readme & MIT license
* Linters setup
* Create React App

### CODE REVIEW

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @Mehdi-Rh , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✅ PRO PR
✅ Github flow
✅ No linter error

## Required Changes ♻️

- [ ]  Please it would be better to use the `README template provided by MICROVERSE and customize it to your own in order for your project will be pro

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by muneebulrehman — APPROVED** [review]
Hi @Mehdi-Rh , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳
Congratulations! 🎉 

# Status: Approved✔️

## Highlights
- Good documentation
- Descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Mehdi-Rh** [comment]
@muneebulrehman Happy that I had you as a reviewer :+1: 
I have just a question,  I have a dev => main  PR, should I merge it before merging this PR

**Comment by muneebulrehman** [comment]
> @muneebulrehman Happy that I had you as a reviewer 👍 I have just a question, I have a dev => main PR, should I merge it before merging this PR

Hey @Mehdi-Rh, nice to see you again. You should only merge dev into main, when all the functionality of the project is working or you know at least this part of the project is perfectly working.

**Comment by Mehdi-Rh** [comment]
I see, thanx Muneeb

**Pull request merged**
